## Query Packages

#### *04 December 2019*
#### *DATA 1010*

In [1]:
using Distributions, Plots, Query, VegaDatasets, DataFrames

*Introduction*. The `DataFrame` is the standard Julia object for storing tabular data:

In [2]:
df = DataFrame(dataset("cars"))

406×9 DataFrame. Omitted printing of 6 columns
│ Row │ Name                              │ Miles_per_Gallon │ Cylinders │
│     │ String                            │ Float64⍰         │ Int64     │
├─────┼───────────────────────────────────┼──────────────────┼───────────┤
│ 1   │ chevrolet chevelle malibu         │ 18.0             │ 8         │
│ 2   │ buick skylark 320                 │ 15.0             │ 8         │
│ 3   │ plymouth satellite                │ 18.0             │ 8         │
│ 4   │ amc rebel sst                     │ 16.0             │ 8         │
│ 5   │ ford torino                       │ 17.0             │ 8         │
│ 6   │ ford galaxie 500                  │ 15.0             │ 8         │
│ 7   │ chevrolet impala                  │ 14.0             │ 8         │
│ 8   │ plymouth fury iii                 │ 14.0             │ 8         │
│ 9   │ pontiac catalina                  │ 14.0             │ 8         │
│ 10  │ amc ambassador dpl                │ 15.0             │ 8         │
⋮
│ 396 │ oldsmobile cutlass ciera (diesel) │ 38.0             │ 6         │
│ 397 │ chrysler lebaron medallion        │ 26.0             │ 4         │
│ 398 │ ford granada l                    │ 22.0             │ 6         │
│ 399 │ toyota celica gt                  │ 32.0             │ 4         │
│ 400 │ dodge charger 2.2                 │ 36.0             │ 4         │
│ 401 │ chevrolet camaro                  │ 27.0             │ 4         │
│ 402 │ ford mustang gl                   │ 27.0             │ 4         │
│ 403 │ vw pickup                         │ 44.0             │ 4         │
│ 404 │ dodge rampage                     │ 32.0             │ 4         │
│ 405 │ ford ranger                       │ 28.0             │ 4         │
│ 406 │ chevy s-10                        │ 31.0             │ 4         │

The analogue of `DataFrame` in Python is `pandas.DataFrame`, and in R you would use either `data.frame` (in base R) or `tibble` (which is part of the [tidyverse](https://www.tidyverse.org) suite of packages).

The default way of interacting with `DataFrame`s is to use elementwise comparisons to get arrays of boolean values which we then use to index the DataFrame:

## Problem 1

Make a boolean array with the same length as the columns of `df`, where the value in each position is 0 if the car in the corresponding row does not have 8 cylinders, and 1 if it does. Use that array to return a DataFrame containing only the rows where the entry in the cylinders column is equal to 8.

This index-based approach is a typical way of performing manipulations with data frames in Python and R, too. But it leaves something to be desired in the way of concisely expressing *intent*. All we really want to say is "grab the rows where the number of cylinders is equal to 8." But instead we're telling the computer specifically how to do that (first compute and store this boolean array computed from the data frame, then index the data frame with that array.). 

If the data were stored in a database, there would be a very nice solution: **use SQL**: 

```SQL
SELECT * FROM cars WHERE Cylinders = 8
```

The idea of **language integrated query** is to bring the expressiveness of a query language inside the language so it can be used for data frames (and other data stores) inside the programming environment. 

---

#### Historical/Pedagogical note

*Language integrated query* properly refers to a technology introduced by Microsoft in 2007 for its .NET languages (C# and friends). In this context, it's usually abbreviated as LINQ. Here we're using the term more generally to refer programming language constructs designed to express queries. This idea was executed beautifully in the R world in a package called `dplyr` (introduced in 2014), and the elegance of that package and its companion packages (ggplot2, tibble, etc.) has been a significant driver of the enthusiasm behind R in recent years. 

More recently, the package `Query` has brought a `dplyr`-like interface to Julia. Meanwhile, Python doesn't have a mainstream equivalent, although many of the core functions we'll learn do have rough equivalents in Pandas. See the [Julia-Python-R cheatsheet](https://data1010.github.io/docs/cheatsheets/jpr-cheatsheet.pdf) for more details. 

After working through this notebook, you should be in good position to use `Query.jl`, pick up `dplyr` by learning a few differences between the two libraries, and apply some of these lessons to Pandas where possible. The exercises will hopefully also help bolster your SQL skills, although SQL's syntax is somewhat different.

---

## Filtering

Here's how we can use Query to filter the rows according to a `Cylinders` value of 8:

In [3]:
df |> @filter(x->x.Cylinders == 8) |> DataFrame

108×9 DataFrame. Omitted printing of 6 columns
│ Row │ Name                                 │ Miles_per_Gallon │ Cylinders │
│     │ String                               │ Float64⍰         │ Int64     │
├─────┼──────────────────────────────────────┼──────────────────┼───────────┤
│ 1   │ chevrolet chevelle malibu            │ 18.0             │ 8         │
│ 2   │ buick skylark 320                    │ 15.0             │ 8         │
│ 3   │ plymouth satellite                   │ 18.0             │ 8         │
│ 4   │ amc rebel sst                        │ 16.0             │ 8         │
│ 5   │ ford torino                          │ 17.0             │ 8         │
│ 6   │ ford galaxie 500                     │ 15.0             │ 8         │
│ 7   │ chevrolet impala                     │ 14.0             │ 8         │
│ 8   │ plymouth fury iii                    │ 14.0             │ 8         │
│ 9   │ pontiac catalina                     │ 14.0             │ 8         │
│ 10  │ amc ambassador dpl                   │ 15.0             │ 8         │
⋮
│ 98  │ chevrolet caprice classic            │ 17.0             │ 8         │
│ 99  │ ford ltd landau                      │ 17.6             │ 8         │
│ 100 │ mercury grand marquis                │ 16.5             │ 8         │
│ 101 │ dodge st. regis                      │ 18.2             │ 8         │
│ 102 │ buick estate wagon (sw)              │ 16.9             │ 8         │
│ 103 │ ford country squire (sw)             │ 15.5             │ 8         │
│ 104 │ chevrolet malibu classic (sw)        │ 19.2             │ 8         │
│ 105 │ chrysler lebaron town @ country (sw) │ 18.5             │ 8         │
│ 106 │ cadillac eldorado                    │ 23.0             │ 8         │
│ 107 │ oldsmobile cutlass salon brougham    │ 23.9             │ 8         │
│ 108 │ oldsmobile cutlass ls                │ 26.6             │ 8         │

We can see that the `@filter` macro takes an anonymous function which it applies to each row. Each row is treated as a `NamedTuple` whose fields can be accessed with dot syntax.

In [4]:
t = (a=1, b=7)
typeof(t)

NamedTuple{(:a, :b),Tuple{Int64,Int64}}

In [5]:
t.a

1

The pipe operator (`|>`) simply forwards the result returned by each expression to the following one. `Query` supports an even more succinct anonymous function syntax where we can drop the arrow and use an underscore for the argument:

In [6]:
df |> @filter(_.Cylinders == 8) |> DataFrame

108×9 DataFrame. Omitted printing of 6 columns
│ Row │ Name                                 │ Miles_per_Gallon │ Cylinders │
│     │ String                               │ Float64⍰         │ Int64     │
├─────┼──────────────────────────────────────┼──────────────────┼───────────┤
│ 1   │ chevrolet chevelle malibu            │ 18.0             │ 8         │
│ 2   │ buick skylark 320                    │ 15.0             │ 8         │
│ 3   │ plymouth satellite                   │ 18.0             │ 8         │
│ 4   │ amc rebel sst                        │ 16.0             │ 8         │
│ 5   │ ford torino                          │ 17.0             │ 8         │
│ 6   │ ford galaxie 500                     │ 15.0             │ 8         │
│ 7   │ chevrolet impala                     │ 14.0             │ 8         │
│ 8   │ plymouth fury iii                    │ 14.0             │ 8         │
│ 9   │ pontiac catalina                     │ 14.0             │ 8         │
│ 10  │ amc ambassador dpl                   │ 15.0             │ 8         │
⋮
│ 98  │ chevrolet caprice classic            │ 17.0             │ 8         │
│ 99  │ ford ltd landau                      │ 17.6             │ 8         │
│ 100 │ mercury grand marquis                │ 16.5             │ 8         │
│ 101 │ dodge st. regis                      │ 18.2             │ 8         │
│ 102 │ buick estate wagon (sw)              │ 16.9             │ 8         │
│ 103 │ ford country squire (sw)             │ 15.5             │ 8         │
│ 104 │ chevrolet malibu classic (sw)        │ 19.2             │ 8         │
│ 105 │ chrysler lebaron town @ country (sw) │ 18.5             │ 8         │
│ 106 │ cadillac eldorado                    │ 23.0             │ 8         │
│ 107 │ oldsmobile cutlass salon brougham    │ 23.9             │ 8         │
│ 108 │ oldsmobile cutlass ls                │ 26.6             │ 8         │

---

## Problem 2

Write a `Query` statement which filters `df` so that the only rows remaining have a `Displacement` value greater than 300 and a `Horsepower` value greater than 150.

---

## Sorting

`@filter` is one of the fundamental data frame manipulations. The second is **sorting**. Suppose we want to see the smallest handful of cars by engine displacement. We can do that with `@orderby`:

In [7]:
df |> @orderby(_.Displacement) |> @take(5) |> DataFrame

5×9 DataFrame. Omitted printing of 5 columns
│ Row │ Name                │ Miles_per_Gallon │ Cylinders │ Displacement │
│     │ String              │ Float64⍰         │ Int64     │ Float64      │
├─────┼─────────────────────┼──────────────────┼───────────┼──────────────┤
│ 1   │ fiat 128            │ 29.0             │ 4         │ 68.0         │
│ 2   │ mazda rx2 coupe     │ 19.0             │ 3         │ 70.0         │
│ 3   │ maxda rx3           │ 18.0             │ 3         │ 70.0         │
│ 4   │ mazda rx-7 gs       │ 23.7             │ 3         │ 70.0         │
│ 5   │ toyota corolla 1200 │ 31.0             │ 4         │ 71.0         │

(Notice that we threw in an extra macro, `@take`, so we can restrict how many rows are printing out in our notebook.)

## Problem 3

Write a query which sorts by weight in descending order (use `@orderby_descending`, or you can negate the weight in your anonymous function).

---

## Selecting

The third dataframe manipulation is **selection**, which is the term for choosing which columns to include. Columns can be specified by name, index, or predicate (in other words, a `Bool`-returning function that can be applied to each column name), and can be excluded with a negative sign.

In [9]:
df |> @select(1:3, :Displacement, -:Miles_per_Gallon, occursin("ear")) |> DataFrame

406×4 DataFrame. Omitted printing of 1 columns
│ Row │ Name                              │ Cylinders │ Displacement │
│     │ String                            │ Int64     │ Float64      │
├─────┼───────────────────────────────────┼───────────┼──────────────┤
│ 1   │ chevrolet chevelle malibu         │ 8         │ 307.0        │
│ 2   │ buick skylark 320                 │ 8         │ 350.0        │
│ 3   │ plymouth satellite                │ 8         │ 318.0        │
│ 4   │ amc rebel sst                     │ 8         │ 304.0        │
│ 5   │ ford torino                       │ 8         │ 302.0        │
│ 6   │ ford galaxie 500                  │ 8         │ 429.0        │
│ 7   │ chevrolet impala                  │ 8         │ 454.0        │
│ 8   │ plymouth fury iii                 │ 8         │ 440.0        │
│ 9   │ pontiac catalina                  │ 8         │ 455.0        │
│ 10  │ amc ambassador dpl                │ 8         │ 390.0        │
⋮
│ 396 │ oldsmobile cutlass ciera (diesel) │ 6         │ 262.0        │
│ 397 │ chrysler lebaron medallion        │ 4         │ 156.0        │
│ 398 │ ford granada l                    │ 6         │ 232.0        │
│ 399 │ toyota celica gt                  │ 4         │ 144.0        │
│ 400 │ dodge charger 2.2                 │ 4         │ 135.0        │
│ 401 │ chevrolet camaro                  │ 4         │ 151.0        │
│ 402 │ ford mustang gl                   │ 4         │ 140.0        │
│ 403 │ vw pickup                         │ 4         │ 97.0         │
│ 404 │ dodge rampage                     │ 4         │ 135.0        │
│ 405 │ ford ranger                       │ 4         │ 120.0        │
│ 406 │ chevy s-10                        │ 4         │ 119.0        │

## Problem 4

Write a query to return a data frame containing only the Saabs, sorted by horsepower, and showing only the name, number of cylinders, and year.

## Problem 5

Suppose you have a data frame which has 200 columns, called `gene1`, `gene2`, ..., `gene200`, each indicating whether a particular subject has a specified allele for the gene in question. Write a query to select just those 200 columns (you may assume that no other columns have the word `gene` in their names).

In [ ]:
allele_df = DataFrame(:haircolor => rand(["black", "blonde", "brown", "red"], 1000), 
                      [Symbol("gene$i") => rand(Bool, 1000) for i in 1:200]...)
allele_df |> @take(5)

---

## Mutating

Another common operation is adding derived columns to a dataframe. For example, in this case, we might want to compute the engine displacement per cylinder. The dplyr/Query language for that operation is **mutate**.

In [10]:
df |> @mutate(disp_per_cyl = _.Displacement/_.Cylinders)

406x10 query result
Name                      │ Miles_per_Gallon │ Cylinders │ Displacement
──────────────────────────┼──────────────────┼───────────┼─────────────
chevrolet chevelle malibu │ 18.0             │ 8         │ 307.0
buick skylark 320         │ 15.0             │ 8         │ 350.0
plymouth satellite        │ 18.0             │ 8         │ 318.0
amc rebel sst             │ 16.0             │ 8         │ 304.0
ford torino               │ 17.0             │ 8         │ 302.0
ford galaxie 500          │ 15.0             │ 8         │ 429.0
chevrolet impala          │ 14.0             │ 8         │ 454.0
plymouth fury iii         │ 14.0             │ 8         │ 440.0
pontiac catalina          │ 14.0             │ 8         │ 455.0
amc ambassador dpl        │ 15.0             │ 8         │ 390.0
... with 396 more rows, and 6 more columns: Horsepower, Weight_in_lbs, Acceleration, Year, Origin, disp_per_cyl

## Problem 6

Write a query which returns a new data frame showing a miles-per-gallon-per-pound value for each row, only includes those rows for which that value is at least 0.005, and only shows that new value, together with the name and the acceleration. Also, only print the first 5 rows of this data frame.

---

## Grouping and aggregating

*Grouping* is a more conceptually challenging operation, since it changes the structure of the data frame. Conceputally, you want to think of grouping as splitting the *rows* of the data frame into groups and making stacks: 

<img src="grouping.svg" width=500px>

Each group has a **key** value (1 or 2 in the example above), and we can access whole columns of each grouping object using dot syntax. For example, we can group on the number of cylinders and take a look at all of the weight values within each cylinder group. Note that we're using `@map` with `@groupby`. These two are usually used in conjunction, since the object returned by the grouping operation is not meant to be used raw.

Also, notice the curly braces in the argument to `@map`. That's special `Query` syntax used to combine the underscore-based anonymous functions with NamedTuples.

In [11]:
df |> @groupby(_.Cylinders) |> @map({n_cylinders = key(_), weight_values = _.Weight_in_lbs})

5x2 query result
n_cylinders
───────────
8
4
6
3
5
... with 1 more column: weight_values

More commonly, we would use `@map` to **aggregate** values within each group. For example, to find the total weight of all the cars in the table with each number of cylinders:

In [12]:
df |> @groupby(_.Cylinders) |> @map({n_cylinders=key(_), total_weight=sum(_.Weight_in_lbs)})

5x2 query result
n_cylinders │ total_weight
────────────┼─────────────
8           │ 443361
4           │ 478726
6           │ 268651
3           │ 9594
5           │ 9310

## Problem 7

Write a `@groupby` query which shows the average engine displacement for each country of origin. Sort the resulting table in decreasing order of average displacement.

---

## Joining

One final operation which plays a major role in the structured database world is the **join**. 

For example, suppose that you have a database in which several different tables need to store information in an "album" field. For example, each user might have a favorite album, each song might have an album associated with it, etc. Each album has associated metadata, like the name of the artist, the year the album was released, the label, etc. To avoid redundancy, it makes sense to record that information in a single `albums` table. Then queries which require composing information in multiple tables (for example, in what year was Deborah's favorite album released?) can be achieved with a join:

In [14]:
people = DataFrame(name = ["Alice", "Bob", "Charlie", "Deborah"], 
                   age = [24, 42, 31, 65], 
                   album = ["A Hard Day's Night", "Yellow Submarine", "Abbey Road", "Yellow Submarine"])
albums = DataFrame(name = ["A Hard Day's Night", "Yellow Submarine", "Abbey Road"], 
                   year = [1964, 1969, 1969])

# the arguments to @join are (1) selector for the outer table, (2) selector for the inner table, and (3) 
# a two-argument anonymous function (_ and __ are the names of the two arguments) which specifies the 
# fields and column names for the output DataFrame
people |> @join(albums, _.album, _.name, {_.name, year_of_favorite_album = __.year}) |> DataFrame

4×2 DataFrame
│ Row │ name    │ year_of_favorite_album │
│     │ String  │ Int64                  │
├─────┼─────────┼────────────────────────┤
│ 1   │ Alice   │ 1964                   │
│ 2   │ Bob     │ 1969                   │
│ 3   │ Charlie │ 1969                   │
│ 4   │ Deborah │ 1969                   │

## Problem 8 

Write a `@join` query to make a table which answers the question "what is the average price of the items purchased by each person?"

In [15]:
purchases = DataFrame(name = ["Alice", "Alice", "Bob", "Bob", "Bob", "Charlie", "Charlie", "Deborah"], 
                      sku = ["KS944RUR", "RJ322RBF", "AB202YUN", "RJ322RBF", "GK216RFR", "RJ322RBF", "AB202YUN", "AK222RGB"])

goods = DataFrame(sku = ["KS944RUR", "RJ322RBF", "AB202YUN", "GK216RFR", "AK222RGB"],
                  price = [24.43, 53.31, 32.13, 97.42, 13.13]);